update-pico8-official
Fix issue with pico8 official not being set as the default emulator after being installed. Recent update now pre-caches(downloads) all viewed games so existing bind mount resulted in a huge amount of clutter. Removed bind mount code and instead now have a gameStop hook that parses for marked favorites and copies those into /roms/pico8/splore

diff --git a/board/batocera/fsoverlay/usr/bin/knulli-install-pico8 b/board/batocera/fsoverlay/usr/bin/knulli-install-pico8
--- a/board/batocera/fsoverlay/usr/bin/knulli-install-pico8
+++ b/board/batocera/fsoverlay/usr/bin/knulli-install-pico8
@@ -13,10 +13,17 @@ PICO_8_DAT_FILE="$TEMP_INSTALL_DIR/pico-8/pico8.dat"
 PICO_8_ES_SYSTEMS_CONFIG=/usr/share/emulationstation/es_systems_pico8.cfg.install
 SPLORE_FILE="$ROMS_DIR/Splore.png"
 
+YAML_FILE="/usr/share/batocera/configgen/configgen-defaults-arch.yml"
+
 PICO_8_ZIPFILE=$(ls -d /userdata/roms/pico8/pico-8*raspi*.zip 2>/dev/null | head -1)
 
 if [ -z $PICO_8_ZIPFILE ] || [ ! -f "$PICO_8_ZIPFILE" ]; then
   echo "Please add the Raspberry Pi version of Pico-8 to roms/pico8 and try again."
+  exit 2
+fi
+
+if [ ! -f "$YAML_FILE" ]; then
+  echo "Unable to install Pico-8: $YAML_FILE missing."
   exit 2
 fi
 
@@ -77,6 +84,18 @@ echo "Set Pico-8 to be executable."
 TARGET_FILE="/userdata/system/configs/emulationstation/es_systems_pico8.cfg"
 cp $PICO_8_ES_SYSTEMS_CONFIG $TARGET_FILE
 echo "Installed emulator configuration for standalone Pico-8."
+
+# Set Pico-8 official as default emulator
+if ! grep -q "^pico8:" "$YAML_FILE"; then
+  cat <<'EOF' >> "$YAML_FILE"
+pico8:
+  emulator: lexaloffle
+  core:     pico8_official
+EOF
+  echo "Added pico8 official to $YAML_FILE"
+else
+  echo "pico8 official already exists in $YAML_FILE"
+fi
 
 if [ ! -f "$SPLORE_FILE" ]; then
     echo "Splore" > "$SPLORE_FILE"
